version: '3'

services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: maxence
      MYSQL_PASSWORD: maxence
      MYSQL_DATABASE: cloud_computing
    networks:
      - private_network
    volumes:
      - db_data:/var/lib/mysql
  web:
    image: maxence1502/cloud_computing:1.1
    restart: always
    ports:
      - "4000:80"
    networks:
      - private_network
    volumes:
      - "/mnt/c/Users/maxence/Desktop/Exercices/Cloud computing/Final project/website:/var/www/html/"
    depends_on:
      - database

volumes:
  db_data:

networks:
  private_network:
    driver: bridge
